[versions]
# Plugins
kotlin = "2.3.0"
kotlinter = "5.2.0"
kotlinx-kover = "0.9.4"
git-version = "4.2.0"
shadow = "8.1.1"
plugin-yml = "0.6.0"
minecraft-server = "4.0.2"

# Libraries
kotlinx-serialization = "1.10.0"
kotlinpoet = "2.2.0"
clikt = "5.1.0"
ktlint = "1.8.0"
slf4j = "2.0.17"
spigot-api = "1.19.4-R0.1-SNAPSHOT"
packetevents = "2.11.2"

[libraries]
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlin" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinpoet = { group = "com.squareup", name = "kotlinpoet", version.ref = "kotlinpoet" }
clikt = { group = "com.github.ajalt.clikt", name = "clikt", version.ref = "clikt" }
ktlint-rule-engine = { group = "com.pinterest.ktlint", name = "ktlint-rule-engine", version.ref = "ktlint" }
ktlint-rule-engine-core = { group = "com.pinterest.ktlint", name = "ktlint-rule-engine-core", version.ref = "ktlint" }
ktlint-ruleset-standard = { group = "com.pinterest.ktlint", name = "ktlint-ruleset-standard", version.ref = "ktlint" }
slf4j = { group = "org.slf4j", name = "slf4j-simple", version.ref = "slf4j" }
spigot-api = { group = "org.spigotmc", name = "spigot-api", version.ref = "spigot-api" }
packetevents-spigot = { group = "com.github.retrooper", name = "packetevents-spigot", version.ref = "packetevents" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlinter = { id = "org.jmailen.kotlinter", version.ref = "kotlinter" }
kotlinx-kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kotlinx-kover" }
git-version = { id = "com.palantir.git-version", version.ref = "git-version" }
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }
plugin-yml-bukkit = { id = "net.minecrell.plugin-yml.bukkit", version.ref = "plugin-yml" }
minecraft-server = { id = "dev.s7a.gradle.minecraft.server", version.ref = "minecraft-server" }
